spring:
  application:
    name: git.test
  datasource:
    url: jdbc:h2:file:./data/employee_db
    username: sa
    password: 123
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
server:
  port: 8080
management:
  endpoints:
    web:
      exposure:
        include: "*"